### ISSUE TITLE
Traefik

### ISSUE THREAD

**Issue by waahhhh** [phpugms/talks#17]
https://traefik.io

Alternative zu Nginx/Apache?
Oder als Instanz vor Nginx/Apache, da man Dank des "reverse proxy / load balancer" einfach skalieren kann?

**Comment by waahhhh** [comment]
Falls man auch einen Speaker vorschlagen darf: https://manuelzapf.io.
47877 Willich ist ein Stück, aber vielleicht ist er trotzdem dabei. ^^

**Comment by waahhhh** [comment]
Könnte wohl einen Lightning Talk halten.
Die Frage ist nur, ob Version 1 oder gleich Version 2.
Falls gewünscht auch nochmal eine Info, wie man von Version 1 nach Version 2 migriert.
(Version 2 steckt noch in der Alpha)

**Comment by bcremer** [comment]
@waahhhh Das klingt doch super. ein 10-20 minuten Lightning Talk können wir für das Meetup am 20. Mai vorsehen. Passt dir das?

**Comment by waahhhh** [comment]
Passt. :+1:

**Comment by waahhhh** [comment]
Talk: https://speakerdeck.com/waahhhh/introduction-to-traefik
Sources für die Github Pages: https://github.com/phpugms/phpugms.github.io/pull/34
