### ISSUE TITLE
Golang for PHP devs

### ISSUE THREAD

**Issue by ndzoesch** [phpugms/talks#20]
## Talk description

The target audience for this talk are php devs not yet familiar with the language [go](https://golang.org/).
The goal of this talk is to show the audience that go is an awesome tool for php devs.

- First, I'll show in what situations the language is useful for php developers and how you can benefit from using it.
  - The core principles of the language are explained, focusing on the concepts that differ from php.
- Secondly, I'll do some live coding to actually show the principles and language features explained before.
- Lastly everything is wrapped up to show the main takeaways for this talk.

I already did a number of talks on this on different conferences, so I'm familiar with how to present the topic. Still, I'll create new slides specifically for phpugms.

In case you want to review the slides beforehand, please let me know.

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [x] German
- [ ] English

I'm able to do the talk in english when needed, but since I'm a native german... :wink: 

## Talk preparation

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time

- [20.03.2019](https://www.meetup.com/de-DE/phpugms/events/zldgbqyzfbzb/)

## Speaker names

- Niklas Dzösch

## Speakers info

- Working at shopware AG as developer evangelist
- Born 1982
- Main programming language: PHP
- Programming in go since somewhat over two years
- Living in Münster
- Linux enthusiast
- Pragmatic

## Twitter handle(s)

- https://twitter.com/ndzoesch

**Comment by bcremer** [comment]
Hey @ndzoesch, that sounds like a great talk.

We are looking forward to see you at our March Meetup on Wednesday, March 20, 2019.

**Comment by bcremer** [comment]
Hey @ndzoesch, thank you again for your talk proposal. We'll announce your talk in tomorrows meetup: https://phpugms.github.io/phpugms_greeting_2019-02/#/14
