### ISSUE TITLE
E2E testing as it should be - Introduction to Cypress

### ISSUE THREAD

**Issue by leichteckig** [phpugms/talks#31]
## Talk description
When it comes to UI testing, some developers tend to be reluctant a lot. Are those tests slow, flaky, hard to write and maintain?

Cypress.io (or Cypress for short) is currently getting a lot of attention when it comes to end-to-end testing. Especially in JavaScript environments Cypress.io seems to be slowly gaining acceptance. It does a lot of things right and is preferable to selenium-based approaches in my opinion.

In my session, I want to introduce Cypress to you and explore its possibilities by writing first tests for the https://phpugms.github.io/ website (or any other if I ned more test cases) - so that we can overcome those concerns together.

## Talk length (in Minutes)

- [ ] Lightning talk (20-30 Minutes)
- [x] Main talk (45-60 Minutes)

## Preferred language

- [x] German (but english is fine if necessary)
- [ ] English

## Talk preparation

Do you need support on preparing your talk by e.g. a practice session or a review of your slides? 
We are happy to help!

- [ ] Yes, ...
- [x] No, thanks.

## Preferred date/time
(You can find all our upcoming events here: https://www.meetup.com/phpugms/events/)

- Starting from mid to end august, anytime :slightly_smiling_face: 

## Speaker names
(Please name all speakers giving this talk.)
Ramona Schwering

## Speakers info
(Optional, your company, your position, etc.)

- 

## Twitter handle(s)
(Optional, we usually announce speakers via https://twitter.com/phpugms)

- https://twitter.com/leichteckig

## Other links
https://github.com/leichteckig

**Comment by bcremer** [comment]
Hey Ramona, thanks for proposing your talk - It sounds fantastic btw :+1: 

I have not yet scheduled an upcoming meeting yet. Would you prefer a remote meetup or a on site meetup?

**Comment by leichteckig** [comment]
Either way is fine for me, remote setup should be ready. :+1: On the other side, I have to admit I miss onside meetups very much (as soon as it's appropriate).

So we can choose what fits best for you and the meetup in general, I think. :)

**Comment by bcremer** [comment]
Hey Ramona, given the situation we'll continue to have online only meetups until further notice. 

The next meetup was scheduled for the 18th August but I would like to postpone it for a week.
Could you do your Talk on Monday 24th of August via Zoom?

**Comment by leichteckig** [comment]
Hi, should be alright. Do you know if we need english as a language? In this case I'd be more comfortable with a bit more time to exercise, but only if it's possible. 🙂

**Comment by bcremer** [comment]
We'll announce the talk in german, that's totally fine. I'll update the meetup page today and announce the event.
Looking forward hearing you :)
