### ISSUE TITLE
Security in Web-Applications

### ISSUE THREAD

**Issue by bcremer** [phpugms/talks#9]

**Comment by marcelthole** [comment]
## Talk description
_WIP_
Security in Web-Applications
- Sicherheit im allgemeinen
- Crypto
- OWASP Top Ten und gegenmaßnahmen


## Talk length (in Minutes)
* [ ]  Lightning talk (20-30 Minutes)
* [x]  Main talk (45-60 Minutes)


## Preferred language
* [x]  German
* [ ]  English


## Talk preparation
Do you need support on preparing your talk by e.g. a practice session or a review of your slides?
We are happy to help!
* [x]  Yes, a review please
* [ ]  No, thanks.


## Preferred date/time
19.02.2019

## Speaker names
* Marcel Thole

## Speakers info
Software Engineer at Check24

## Twitter handle(s)
 * https://twitter.com/Marcelthole

## Other links
(Optional, Blog, github, medium, facebook, etc.)
* none
